version: "3"
services:
  web:
    image: nginx
    container_name: web-repl
    ports:
      - 8083:80
        #- 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  repl:
    build: .
    container_name: repl